### ISSUE TITLE
Dockeres cppcheck (workflow) meghasal

### ISSUE THREAD

**Issue by kalmar-adam** [Teaching-projects/SZE-MOSZE-2020-TeamlessName#12]
GHA: Test workflow
https://github.com/Teaching-projects/SZE-MOSZE-2020-TeamlessName/runs/1373552068?check_suite_focus=true
@hegyhati @oliverosz 
Ezt a hibaüzit dobja ki a GHA, amikor dockeres image alól szeretném működtetni. Érdekes módon a nem-dockeres workflow lazán lefut. Teljesen tanácstalanok vagyunk, hogy ilyenkor mit kéne tennünk. Minden szükséges csomag fel van rakva a dockeres img-be, hiszen elkezd melózni a cppcheck-el, azaz a parancsot gond nélkül tudja futtatni, csak 2-es kódú errort dob.
A JSON.cpp-be include-olásra kerül az Exceptions.h és az ezekben lévő referencia jelekre panaszkodik a dockeres cppcheck.
Mit csinálunk rosszul?

**Comment by eriklorincz** [comment]
A teljesen tanácstalan azért nem igaz. Ha nem referencia szerint, hanem érték szerint adom át a stringeket akkor nem dobja a hibaüzenetet.

**Comment by oliverosz** [comment]
Ez tényleg fura hiba. Nincs ott semmi dereferenced pointer, ami nullptr lehetne. Mintha a cppcheck pointernek nézné a referenciát. Ez valami cppcheck bug lehet, de a legfrissebb verzió is kiírja ezt az errort. Kipróbáltam egy minimal working example-re, és ott nem tudtam reprodukálni. Érdekes...
Mindegy, most hogy ne okozzon gondot ez a hiba, suppressáltam az errort és felcommitoltam a branchre a patchet.

**Comment by eriklorincz** [comment]
@oliverosz 
Eldugott fórumoldalakon lehet találkozni csak ezzel a hibával, és ott is mindig az a konklúzió, hogy valószínűleg false positive, de soha nem tudják reprodukálni.
Minden esetre köszönjük a segítséget.
