### ISSUE TITLE
gh-pages - Nincs settings lehetőség

### ISSUE THREAD

**Issue by kalmar-adam** [Teaching-projects/SZE-MOSZE-2020-TeamlessName#3]
Nincs settings lehetőség, amivel source-nak tudom állítani a gh-pages-t. Önök tudnak ebben segíteni adminként vagy én nem tudom csak mit kéne tennem?
EDIT: Azért nyitottam Issue-t, mert szerintem @hegyhati erre referált, amikor másnak is ilyen gondja/baja volt.
@vizvezetek @hegyhati

**Comment by hegyhati** [comment]
Teljesen jol tetted, azt viszont nem irtad meg, hogy melyik branch melyik konyvtarara legyen beallitva. megcsinaltam `gh-pages/(root)`-ra, ha igy jo, lezarhatod az issue-t.

**Comment by kalmar-adam** [comment]
Tökéletes, pont így szerettem volna! Nagyon szépen köszönöm! <3
