### ISSUE TITLE
Kérelem: VoicePlay csapat a mi reponkhoz hozzárendelése triage joggal

### ISSUE THREAD

**Issue by kalmar-adam** [Teaching-projects/SZE-MOSZE-2020-TeamlessName#8]
@hegyhati 
Nagyon szépen kérnénk, hogy a VoicePlay csapatot ( @vbence121 @kkira07 @VMatthew ) triage joggal rendelje hozzá a mi reponkhoz! Előre is nagyon szépen köszönjük!

**Comment by kalmar-adam** [comment]
@hegyhati Elnézést kérek, ha ez sürgetésnek tűnik, de esélytelennek tűnik holnap reggelre befejezni a feladatot ha tovább kell várnunk a csapat hozzánk rendelésére!

**Comment by hegyhati** [comment]
Tekintve hogy volt kb 2 hetetek kinyitni ezt az issue-t, engem meg 24 oran belul piszkaltok, valoban anak tunik, de elmeletileg done.

**Comment by kalmar-adam** [comment]
> 
> 
> Tekintve hogy volt kb 2 hetetek kinyitni ezt az issue-t, engem meg 24 oran belul piszkaltok, valoban anak tunik, de elmeletileg done.

@hegyhati Elnézését kérem! Valóban így nem volt fair ez az eljárás részemről! Legközelebb igyekszem jobban számításba venni a issue/review/pr kezelésének idő és energia igényét és ezeket lehetőleg minél előbb meglépni, ha van rá mód! Nagyon szépen köszönöm és ismételten kérem elnézését!

**Comment by hegyhati** [comment]
Tultargyalva, lesson learned. hajra.
